### ISSUE TITLE
Create contributing docs

### ISSUE THREAD

**Issue by threedot14** [mhsengineering/mhsengineering.github.io#4]
A lot of people seem eager to contribute to the website (props to @johntheawesomeguy for doing nearly all the work so far) but the contributions seem messy. We should require people to use descriptive commit messages and only commit relatively working content. We should never push a live site that isn't in working condition.

This may take some education on our part. Contributors should know how to test locally and understand what separates a good commit from a bad commit. @50Wliu recommended requiring pull requests (i.e. all commits will need to be reviewed before landing in the main repository).

**Comment by 50Wliu** [comment]
1. Make sure you have a descriptive commit message.  fa2ab80 is an example of a good commit message ("Put all styles in one stylesheet", with an additional description), while a generic "update" or "Update about.html"  doesn't tell us much.  Strive to make commit messages that are under 50 characters (they really shouldn't be longer than 80) - they're meant to describe the commit at a glance.  Anything else can go in the description.  Here are some useful links for inspiration: [erlang/otp wiki](https://github.com/erlang/otp/wiki/Writing-good-commit-messages), [atom/atom CONTRIBUTING.md](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#git-commit-messages), [chris.beams.io on seven good commit rules](http://chris.beams.io/posts/git-commit/#seven-rules)
2.  Test changes locally.  This will only be required until (if ever) we get automated testing of the website set up.  There are a couple ways of testing your changes:
  * Using [Github Desktop](https://desktop.github.com) (Windows and Mac only; if you're on Linux I really shouldn't need to tell you what to use).  It comes with a nice tutorial to get you started.
  * If on a Chromebook, there's a bunch of different options.  You can start by downloading a [zip file](https://github.com/mhsengineering/mhsengineering.github.io/archive/master.zip) of the website and going from there.  We'll probably discuss more options at the next meeting.
  * You can also create your own [branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/), and then mess around in it to your heart's content.  Changes in your branch will not be reflected on the website.  When you're happy with the changes, create a pull request as described in the next point.
3.  Use [pull requests](https://help.github.com/articles/using-pull-requests/) (as Eric mentioned).  Pull requests allow others to review your changes so that we can be extra sure that everything looks ok.  They're also a convenient place to discuss about the changes (and you can even leave inline comments) rather than sending emails back and forth.  If/when automated testing is set up this will become mandatory to make sure your changes are valid.

That's all for now I think.  May add more later.

Pinging everyone who's not already watching this repository so that they get a notification:
@andrewrosenkilde 
@Dantheman9069 
@EastTOWes 
@johntheawesomeguy 
@Mellan88

**Comment by threedot14** [comment]
Closing on account of f023b51f2f03f07e96205ad8f36af7c10ae61842 solves this problem.
